# Site settings
title: Rogue Hack Lab
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rogue Hack Lab
user_description: We do stuff
user_title: Medford, Oregon
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
