[build]
  publish = "public"
  command = "HUGO_BASEURL=$URL hugo --minify; npm run build:functions"
  functions = "./functions-build"


[build.environment]
  HUGO_VERSION = "0.57.2"

[context.deploy-preview]
  command = "HUGO_BASEURL=$DEPLOY_PRIME_URL hugo --i18n-warnings"

[context.deploy-preview.environment]
  HUGO_GOOGLEANALYTICS = "dev"

[context.production.environment]
  HUGO_ENV = "production"